/**
 * Placeholder rows for the search results grid, and the docket detail view
 * opened from a row (see SearchResultsPage's onRowClick and
 * Form1/components/DocketDetailView.jsx), so both can be reviewed with data
 * in them.
 *
 * TODO: delete this once useSearchResultsPage and DocketDetailView are wired
 * to the real DDS search / get-docket endpoints - see the TODOs there.
 */
export const DUMMY_SEARCH_RESULTS = [
  {
    docketId: 1,
    docketNo: '1935197',
    caseName: 'SIXTOS, JESUS',
    caseType: 'ALS',
    county: 'Fulton',
    dateReceived: '2026-01-05',
    dateRequested: '2026-01-04',
    dateEntered: '2026-01-06',
    hearingDate: '2026-02-12',
    hearingTime: '09:00:00',
    hearingLocation: 'Atlanta',
    hearingType: 'In Person',
    status: 'Draft',
    judge: 'Harrison, Marcus',
    judgeAssistant: 'Cole, Priya',
    agencyRefNumber: '059263583',
    eligibleForPermit: 'Yes',
    permitEffectiveDate: '2026-02-20',
    permitExpirationDate: '2026-08-20',
    dateOfBirth: '1964-06-21',
    incidentDate: '2025-12-09',
    parties: [
      {
        role: 'Petitioner Attorney',
        name: 'HOWARD, BRYAN',
        phone: '6783103476',
        email: 'bryan@howardandarca.com',
        fax: '7708365211',
      },
      {
        role: 'Petitioner',
        name: 'SIXTOS, JESUS',
        phone: '',
        email: '',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_1935197.pdf',
        date: '01/04/2026',
        description: 'Original Form 1 application.',
      },
      {
        id: 2,
        documentType: 'Notice of Hearing',
        name: 'NOH_1935197.pdf',
        date: '01/06/2026',
        description: 'Initial notice of hearing sent to parties.',
      },
    ],
  },
  {
    docketId: 2,
    docketNo: '1935198',
    caseName: 'JOHNSON, DAWANA',
    caseType: 'ALS',
    county: 'Fulton',
    dateReceived: '2026-01-06',
    dateRequested: '2026-01-05',
    dateEntered: '2026-01-07',
    hearingDate: '2026-02-12',
    hearingTime: '09:30:00',
    hearingLocation: 'Atlanta',
    hearingType: 'In Person',
    status: 'Scheduled',
    judge: 'Harrison, Marcus',
    judgeAssistant: 'Cole, Priya',
    agencyRefNumber: '059263591',
    eligibleForPermit: 'No',
    permitEffectiveDate: '',
    permitExpirationDate: '',
    dateOfBirth: '1979-03-11',
    incidentDate: '2025-12-10',
    parties: [
      {
        role: 'Petitioner',
        name: 'JOHNSON, DAWANA',
        phone: '4045550123',
        email: 'dawana.johnson@example.com',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_1935198.pdf',
        date: '01/05/2026',
        description: 'Original Form 1 application.',
      },
      {
        id: 2,
        documentType: 'Notice of Hearing',
        name: 'NOH_1935198.pdf',
        date: '01/07/2026',
        description: 'Initial notice of hearing sent to parties.',
      },
    ],
  },
  {
    docketId: 3,
    docketNo: '1935199',
    caseName: 'FINDLEY, SHAYNE',
    caseType: 'ALS',
    county: 'Bibb',
    dateReceived: '2026-01-06',
    dateRequested: '2026-01-05',
    dateEntered: '2026-01-07',
    hearingDate: '2026-02-13',
    hearingTime: '10:00:00',
    hearingLocation: 'Macon',
    hearingType: 'Telephone',
    status: 'Scheduled',
    judge: 'Patel, Nina',
    judgeAssistant: 'Ortiz, Marco',
    agencyRefNumber: '059263604',
    eligibleForPermit: 'Yes',
    permitEffectiveDate: '2026-02-21',
    permitExpirationDate: '2026-08-21',
    dateOfBirth: '1988-09-02',
    incidentDate: '2025-12-11',
    parties: [
      {
        role: 'Petitioner',
        name: 'FINDLEY, SHAYNE',
        phone: '4785550188',
        email: '',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_1935199.pdf',
        date: '01/05/2026',
        description: 'Original Form 1 application.',
      },
    ],
  },
  {
    docketId: 4,
    docketNo: '1935200',
    caseName: 'LEWIS, JOHN',
    caseType: 'ALS',
    county: 'Bibb',
    dateReceived: '2026-01-07',
    dateRequested: '2026-01-06',
    dateEntered: '2026-01-08',
    hearingDate: '2026-02-13',
    hearingTime: '10:30:00',
    hearingLocation: 'Macon',
    hearingType: 'In Person',
    status: 'Closed',
    judge: 'Patel, Nina',
    judgeAssistant: 'Ortiz, Marco',
    agencyRefNumber: '059263617',
    eligibleForPermit: 'No',
    permitEffectiveDate: '',
    permitExpirationDate: '',
    dateOfBirth: '1971-01-30',
    incidentDate: '2025-12-12',
    parties: [
      {
        role: 'Petitioner',
        name: 'LEWIS, JOHN',
        phone: '4785550199',
        email: 'john.lewis@example.com',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_1935200.pdf',
        date: '01/06/2026',
        description: 'Original Form 1 application.',
      },
      {
        id: 2,
        documentType: 'Final Order',
        name: 'Order_1935200.pdf',
        date: '02/13/2026',
        description: 'Final order closing the docket.',
      },
    ],
  },
  {
    docketId: 5,
    docketNo: '1935201',
    caseName: 'WALKER, TAMIKA',
    caseType: 'License Revocation',
    county: 'Chatham',
    dateReceived: '2026-01-08',
    dateRequested: '2026-01-07',
    dateEntered: '2026-01-09',
    hearingDate: '2026-02-14',
    hearingTime: '13:00:00',
    hearingLocation: 'Savannah',
    hearingType: 'In Person',
    status: 'Scheduled',
    judge: 'Okafor, Daniel',
    judgeAssistant: 'Blake, Simone',
    agencyRefNumber: '059263629',
    eligibleForPermit: 'Yes',
    permitEffectiveDate: '2026-02-22',
    permitExpirationDate: '2026-08-22',
    dateOfBirth: '1990-07-14',
    incidentDate: '2025-12-13',
    parties: [
      {
        role: 'Petitioner Attorney',
        name: 'CHEN, ALICE',
        phone: '9125550142',
        email: 'alice.chen@example.com',
        fax: '9125550143',
      },
      {
        role: 'Petitioner',
        name: 'WALKER, TAMIKA',
        phone: '',
        email: '',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_1935201.pdf',
        date: '01/07/2026',
        description: 'Original Form 1 application.',
      },
      {
        id: 2,
        documentType: 'Notice of Hearing',
        name: 'NOH_1935201.pdf',
        date: '01/09/2026',
        description: 'Initial notice of hearing sent to parties.',
      },
    ],
  },
  {
    docketId: 6,
    docketNo: '1828555',
    caseName: 'RAMIREZ, CARLOS',
    caseType: 'License Revocation',
    county: 'Chatham',
    dateReceived: '2026-01-08',
    dateRequested: '2026-01-07',
    dateEntered: '2026-01-09',
    hearingDate: '2026-02-14',
    hearingTime: '13:30:00',
    hearingLocation: 'Savannah',
    hearingType: 'Video',
    status: 'Draft',
    judge: 'Okafor, Daniel',
    judgeAssistant: 'Blake, Simone',
    agencyRefNumber: '059263631',
    eligibleForPermit: 'No',
    permitEffectiveDate: '',
    permitExpirationDate: '',
    dateOfBirth: '1983-04-25',
    incidentDate: '2025-12-14',
    parties: [
      {
        role: 'Petitioner',
        name: 'RAMIREZ, CARLOS',
        phone: '9125550166',
        email: '',
        fax: '',
      },
    ],
  },
  {
    docketId: 7,
    docketNo: '2015128',
    caseName: 'NGUYEN, LINH',
    caseType: 'ALS',
    county: 'Muscogee',
    dateReceived: '2026-01-09',
    dateRequested: '2026-01-08',
    dateEntered: '2026-01-10',
    hearingDate: '2026-02-17',
    hearingTime: '09:00:00',
    hearingLocation: 'Columbus',
    hearingType: 'In Person',
    status: 'Continued',
    judge: 'Harrison, Marcus',
    judgeAssistant: 'Cole, Priya',
    agencyRefNumber: '059263648',
    eligibleForPermit: 'Yes',
    permitEffectiveDate: '2026-02-25',
    permitExpirationDate: '2026-08-25',
    dateOfBirth: '1995-11-19',
    incidentDate: '2025-12-15',
    parties: [
      {
        role: 'Petitioner',
        name: 'NGUYEN, LINH',
        phone: '7065550177',
        email: 'linh.nguyen@example.com',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_2015128.pdf',
        date: '01/08/2026',
        description: 'Original Form 1 application.',
      },
      {
        id: 2,
        documentType: 'Continuance Request',
        name: 'Continuance_2015128.pdf',
        date: '02/10/2026',
        description: 'Petitioner requested a continuance of the hearing.',
      },
    ],
  },
  {
    docketId: 8,
    docketNo: '2007968',
    caseName: 'THOMPSON, BRIANNA',
    caseType: 'ALS',
    county: 'Muscogee',
    dateReceived: '2026-01-09',
    dateRequested: '2026-01-08',
    dateEntered: '2026-01-10',
    hearingDate: '2026-02-17',
    hearingTime: '09:30:00',
    hearingLocation: 'Columbus',
    hearingType: 'Telephone',
    status: 'Scheduled',
    judge: 'Reyes, Camille',
    judgeAssistant: 'Diallo, Amara',
    agencyRefNumber: '059263652',
    eligibleForPermit: 'No',
    permitEffectiveDate: '',
    permitExpirationDate: '',
    dateOfBirth: '1992-02-08',
    incidentDate: '2025-12-16',
    parties: [
      {
        role: 'Petitioner',
        name: 'THOMPSON, BRIANNA',
        phone: '7065550183',
        email: '',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_2007968.pdf',
        date: '01/08/2026',
        description: 'Original Form 1 application.',
      },
    ],
  },
  {
    docketId: 9,
    docketNo: '2007966',
    caseName: 'GARCIA, MIGUEL',
    caseType: 'Habitual Violator',
    county: 'Fulton',
    dateReceived: '2026-01-10',
    dateRequested: '2026-01-09',
    dateEntered: '2026-01-11',
    hearingDate: '2026-02-18',
    hearingTime: '11:00:00',
    hearingLocation: 'Atlanta',
    hearingType: 'In Person',
    status: 'Scheduled',
    judge: 'Reyes, Camille',
    judgeAssistant: 'Diallo, Amara',
    agencyRefNumber: '059263665',
    eligibleForPermit: 'No',
    permitEffectiveDate: '',
    permitExpirationDate: '',
    dateOfBirth: '1980-05-27',
    incidentDate: '2025-12-17',
    parties: [
      {
        role: 'Petitioner Attorney',
        name: 'WRIGHT, DESMOND',
        phone: '4045550210',
        email: 'desmond.wright@example.com',
        fax: '4045550211',
      },
      {
        role: 'Petitioner',
        name: 'GARCIA, MIGUEL',
        phone: '',
        email: '',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_2007966.pdf',
        date: '01/09/2026',
        description: 'Original Form 1 application.',
      },
      {
        id: 2,
        documentType: 'Notice of Hearing',
        name: 'NOH_2007966.pdf',
        date: '01/11/2026',
        description: 'Initial notice of hearing sent to parties.',
      },
    ],
  },
  {
    docketId: 10,
    docketNo: '1824161',
    caseName: 'BROOKS, DESTINY',
    caseType: 'ALS',
    county: 'Bibb',
    dateReceived: '2026-01-12',
    dateRequested: '2026-01-11',
    dateEntered: '2026-01-13',
    hearingDate: '2026-02-19',
    hearingTime: '14:00:00',
    hearingLocation: 'Macon',
    hearingType: 'In Person',
    status: 'Closed',
    judge: 'Patel, Nina',
    judgeAssistant: 'Ortiz, Marco',
    agencyRefNumber: '059263679',
    eligibleForPermit: 'Yes',
    permitEffectiveDate: '2026-02-27',
    permitExpirationDate: '2026-08-27',
    dateOfBirth: '1997-08-16',
    incidentDate: '2025-12-18',
    parties: [
      {
        role: 'Petitioner',
        name: 'BROOKS, DESTINY',
        phone: '4785550221',
        email: '',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_1824161.pdf',
        date: '01/11/2026',
        description: 'Original Form 1 application.',
      },
      {
        id: 2,
        documentType: 'Final Order',
        name: 'Order_1824161.pdf',
        date: '02/20/2026',
        description: 'Final order closing the docket.',
      },
    ],
  },
  {
    docketId: 11,
    docketNo: '1828500',
    caseName: 'KIM, SOOJIN',
    caseType: 'License Revocation',
    county: 'Chatham',
    dateReceived: '2026-01-13',
    dateRequested: '2026-01-12',
    dateEntered: '2026-01-14',
    hearingDate: '2026-02-19',
    hearingTime: '14:30:00',
    hearingLocation: 'Savannah',
    hearingType: 'Video',
    status: 'Draft',
    judge: 'Okafor, Daniel',
    judgeAssistant: 'Blake, Simone',
    agencyRefNumber: '059263681',
    eligibleForPermit: 'No',
    permitEffectiveDate: '',
    permitExpirationDate: '',
    dateOfBirth: '1986-10-05',
    incidentDate: '2025-12-19',
    parties: [
      {
        role: 'Petitioner',
        name: 'KIM, SOOJIN',
        phone: '9125550234',
        email: 'soojin.kim@example.com',
        fax: '',
      },
    ],
  },
  {
    docketId: 12,
    docketNo: '1935202',
    caseName: 'MITCHELL, TYLER',
    caseType: 'ALS',
    county: 'Muscogee',
    dateReceived: '2026-01-14',
    dateRequested: '2026-01-13',
    dateEntered: '2026-01-15',
    hearingDate: '2026-02-20',
    hearingTime: '09:00:00',
    hearingLocation: 'Columbus',
    hearingType: 'In Person',
    status: 'Scheduled',
    judge: 'Harrison, Marcus',
    judgeAssistant: 'Cole, Priya',
    agencyRefNumber: '059263694',
    eligibleForPermit: 'Yes',
    permitEffectiveDate: '2026-02-28',
    permitExpirationDate: '2026-08-28',
    dateOfBirth: '1999-12-23',
    incidentDate: '2025-12-20',
    parties: [
      {
        role: 'Petitioner',
        name: 'MITCHELL, TYLER',
        phone: '7065550245',
        email: '',
        fax: '',
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Application',
        name: 'Form1_1935202.pdf',
        date: '01/13/2026',
        description: 'Original Form 1 application.',
      },
      {
        id: 2,
        documentType: 'Notice of Hearing',
        name: 'NOH_1935202.pdf',
        date: '01/15/2026',
        description: 'Initial notice of hearing sent to parties.',
      },
    ],
  },
];
